//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBAF.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MBAFEntities : DbContext
    {
        public MBAFEntities()
            : base("name=MBAFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AudienceType> AudienceType { get; set; }
        public virtual DbSet<AudienceTypeLOG> AudienceTypeLOG { get; set; }
        public virtual DbSet<AudType> AudType { get; set; }
        public virtual DbSet<Corps> Corps { get; set; }
        public virtual DbSet<CorpsLOG> CorpsLOG { get; set; }
        public virtual DbSet<Password> Password { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
        public virtual DbSet<TeacherLOG> TeacherLOG { get; set; }
    
        public virtual ObjectResult<Nullable<int>> GetCountOfAllRecords()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetCountOfAllRecords");
        }
    }
}
