//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBAF.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Password
    {
        public int Id { get; set; }
        public Nullable<int> Password1 { get; set; }
    }
}
