//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBAF.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherLOG
    {
        public int LogId { get; set; }
        public Nullable<int> Id { get; set; }
        public string Fname { get; set; }
        public string Mname { get; set; }
        public string Lname { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string operation { get; set; }
        public Nullable<System.DateTime> operation_dt { get; set; }
        public string operation_user { get; set; }
    }
}
